version: "3.4"

services:
    votor:
      build: ./votor
      ports:
        - 8081:44358
        - 8082:64913
      depends_on:
        - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
